# Generated by Django 4.1.1 on 2022-09-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
