# Generated by Django 4.1.1 on 2022-09-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriptions',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscribers_id',
            new_name='subscriptions_id',
        ),
    ]
