# Generated by Django 4.1.1 on 2022-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_rename_subscriptions_subscription_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='URL'),
        ),
    ]
