# Generated by Django 4.1.1 on 2022-10-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_note_disliked_user_remove_note_liked_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='likes',
        ),
    ]
