# Generated by Django 4.1.1 on 2022-10-17 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_note_dislikes_remove_note_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
