# Generated by Django 4.1.1 on 2022-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_note_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
