# Generated by Django 4.1.1 on 2022-10-28 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_follower_alter_user_photo_delete_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
