# Generated by Django 4.1.1 on 2022-11-06 09:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_follower_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=5000, validators=[django.core.validators.MinLengthValidator(20, 'Поле должно содержать не менее 20 символов')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_creator', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='note',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_user', to=settings.AUTH_USER_MODEL, verbose_name='Поставили дизлайк'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(related_name='liked_user', to=settings.AUTH_USER_MODEL, verbose_name='Поставили лайк'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10, 'Поле должно содержать не менее 10 символов')], verbose_name='Заголовок'),
        ),
    ]
