# Generated by Django 4.1.1 on 2023-01-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_follower_subscriber_alter_follower_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='note',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_notes', to=settings.AUTH_USER_MODEL, verbose_name='Поставили дизлайк'),
        ),
        migrations.AlterField(
            model_name='note',
            name='likes',
            field=models.ManyToManyField(related_name='liked_notes', to=settings.AUTH_USER_MODEL, verbose_name='Поставили лайк'),
        ),
    ]
